### ISSUE TITLE
docker compose up operation is forbidden by GitHub Actions 

### ISSUE THREAD

**Issue by iAmBipinPaul** [actions/docker#11]
I'm trying to run docker compose and I'm getting error as `This Docker operation is forbidden by GitHub Actions, you can find documentation at https://developer.github.com/actions/`

Basically , I created a custom docker image with dotnet core 2.2 , docker , docker  compose and cake build , now when  cake build is trying to run docker compose getting  the above mention error.
(**also getting same error when trying to run docker compose as one action**)

Custom docker file repository https://github.com/iAmBipinPaul/.NETDockerCake
build log : https://github.com/iAmBipinPaul/AspNetCoreDevOps/runs/44274863
Command : `docker-compose up -d --build`

**Comment by sburns** [comment]
The issue is that creating docker networks is not allowed in GitHub Actions and compose does this implicitly. I'm hoping that restriction is removed in the future.

**Comment by iAmBipinPaul** [comment]
Now docker compose is available on **GitHub Action** (with CICD ) so may be we should close this issue.

https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions

![image](https://user-images.githubusercontent.com/9201481/64471787-69ec8d80-d175-11e9-9b37-f7376c1ebf92.png)

and it works as expected.


![image](https://user-images.githubusercontent.com/9201481/64471754-05c9c980-d175-11e9-80f5-14a1a9d22ab3.png)

**Comment by steebchen** [comment]
Yep, that's correct. Please do close the issue.
