### ISSUE TITLE
Docker Load is not supported

### ISSUE THREAD

**Issue by thoughtpolice** [actions/docker#15]
I am using a tool called [Nix](https://nixos.org/nix) to manage dependencies and build very concise docker containers. In particular, one of my custom Actions runs Nix and builds a docker `image.tar.gz` which is put inside the workspace.

However, when trying to chain this with the `cli` command, `docker load` does not work. For example, if my workflow has a "Docker Load" action like:

```
action "Nix Docker Build" {
  uses = "./.github/actions/nix-build"
  args = "release.nix docker image.tar.gz"
}

action "Docker Load" {
  uses = "actions/docker/cli@master"
  needs = ["Nix Docker Build"]
  args = "load -i image.tar.gz"
}
```

The first builds the `image.tar.g`, and the second tries to `load` it. But I get:

```
Error response from daemon: This Docker operation is forbidden by GitHub Actions,
you can find documentation at https://developer.github.com/actions/
```

However, there's no real explanation of this limitation.

-----

My motivation is that the `image.tar.gz` is a Docker image I'd like to load, run tests against (it can "self test" its own binary with no other files needed), then publish to the hub.

The alternative is to "invert" things so I use `docker/cli` to run `build` on a Dockerfile that populates a container, and then maybe use that... But it'd be somewhat difficult to do that... But maybe that has other advantages (shorter shared build time, etc).

I'm just looking for suggestions or any workarounds, and reporting this in case anyone else comes across it.

**Comment by thoughtpolice** [comment]
As a note, I was able to get around this by writing my own tagging script and using `skopeo` in order to push a `docker-archive:` directly to DockerHub.

This Action is fairly generic so hopefully I can just release it soon.

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
