### ISSUE TITLE
Docker login does not properly work with passwords that contain spaces

### ISSUE THREAD

**Issue by thoughtpolice** [actions/docker#16]
I always use 1Password for all my accounts, which comes with a password generator that generates "diceware passwords" that consist of a large string of ordinary words, like `horse bad montana phone` or something. I use this even for my Docker Hub accounts.

However, the default Docker Login action does not support these kinds of passwords, because the `$DOCKER_PASSWORD` variable is not properly interpolated in the `docker login` command -- because `$DOCKER_PASSWORD` is unquoted, a command like:

`docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD`

becomes:

`docker login -u foobar -p horse bad montana phone`

which is interpreted as multiple commands, causing a failure. Quoting would properly distribute this as:

`docker login -u foobar -p 'horse bad montana phone'`

-----

I'm not sure what the semantics of Docker's `ENTRYPOINT` are or if adding a quote directly in the `ENTRYPOINT` line will fix it, or if a separate `entrypoint.sh` using bash to do quoting is necessary.

**Comment by nhumrich** [comment]
just add double quotes. `docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"`
