### ISSUE TITLE
Docker Compose build is forbidden

### ISSUE THREAD

**Issue by sagebind** [actions/docker#17]
Building images via Docker Compose does not seem to be allowed:

```
action "Build image" {
  uses = "docker://docker/compose:1.23.2"
  args = "build"
}
```

fails with

```
This Docker operation is forbidden by GitHub Actions, you can find documentation at https://developer.github.com/actions/
```

but building images manually via the Docker cli does work:

```
action "Build image" {
  uses = "actions/docker/cli@master"
  args = "build -t username/myimage ."
}
```

I'm not sure what Compose is trying to do outside a simple build that causes it to fail, but I feel like `docker-compose build` is a common use-case that should be supported.

**Comment by sunfmin** [comment]
👍 docker compose should be supported.

**Comment by aequitas** [comment]
Running into the same issue: https://github.com/aequitas/Internet.nl-dashboard/runs/98988817

https://github.com/aequitas/Internet.nl-dashboard/blob/development/.github/main.workflow?short_path=4e12f94#L40-L44

In my case I'm doing a `up` instead of `build`.

**Comment by aequitas** [comment]
So diving a little further it seems the network operations are not allowed:
```
Using configuration files: ./docker-compose.yml
Trying paths: ['/github/home/.docker/config.json', '/github/home/.dockercfg']
Found file at path: /github/home/.docker/config.json
Found 'auths' section
Found entry (registry='https://index.docker.io/v1/', username='internetstandards')
http://localhost:None "GET /v1.25/networks/workspace_default HTTP/1.1" 403 141
This Docker operation is forbidden by GitHub Actions, you can find documentation at https://developer.github.com/actions/
```

**Comment by vitorleal** [comment]
I use docker compose to run my tests with a database, and to do so i use docker-compose to run the full tests. I had the same problem when trying to update my pipeline to use Github actions.

In my case I'm doing a `docker-compose run mix test`

**Comment by mklarmann** [comment]
We have the same issue, as we tried to move our build back from gitlab to github actions. Is there a timeline, that this will available?

**Comment by anthonator** [comment]
According to the new Actions beta documentation `docker-compose` is supported.

> Testing multi-container apps? You can now test your web service and its database together by simply adding some docker-compose to your workflow file.

**Comment by anthonator** [comment]
https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/#fast-ci-cd-for-any-os-any-language-and-any-cloud

**Comment by peter-evans** [comment]
This is an example workflow I tested using `docker-compose`.
https://github.com/peter-evans/docker-compose-actions-workflow

**Comment by steebchen** [comment]
I guess this can be closed, as it was only valid for the old actions.

**Comment by sagebind** [comment]
That explains the radio silence then. 😉 

"Hey, we want to support Docker Compose; we're working on a complete refresh of Actions that will support it, but we have not even announced it yet, so please keep this a secret."

**Comment by hfaulds** [comment]
I think you understand but sorry about the lack of communication and yes I believe we can close this now.
