### ISSUE TITLE
Label versioning is prohibited by inspect

### ISSUE THREAD

**Issue by kddeisz** [actions/docker#19]
This is similar to #6, but slightly different. #6 points out the `docker inspect` is not allowed by the task runner. This actually ends up being worse than just wasted commands because it ends up only tagging with the git ref, so the label is effectively useless.

Only two solutions I can think of are to whitelist the inspect command or to allow you to pass a dockerfile as part of the env and then parse it in ruby to get the label manually.

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
