### ISSUE TITLE
docker login stores unencrypted password

### ISSUE THREAD

**Issue by maxheld83** [actions/docker#20]
docker login seems to be a kind of footgun:

```
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /github/home/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```

Is that true?
Or does the action do something smarter?

If not, maybe this isn't such a good idea since it may be easy to pull the images?

**Comment by 1138-4EB** [comment]
@maxheld83, did you receive any reply/comment about this by any other channel? According to https://github.com/actions/docker/blob/master/login/Dockerfile#L13, it seems that no [docker-credential-helper](https://github.com/docker/docker-credential-helpers) is used. I contaced [support](https://github.com/contact) but I didn't receive a reply yet.

**Comment by maxheld83** [comment]
I did not separately contact support about this, according to my records, and also didn't hear back separately.

I am not sure whether this issue is still current.

**Comment by 1138-4EB** [comment]
> and also didn't hear back separately.

That's a pity...

> I am not sure whether this issue is still current.

I do think so:

- The Dockerfile didn't change.
- #27 does not change it.
- Running `echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin` on `ubuntu-latest` is not an option, since the same warning is shown.

**Comment by 1138-4EB** [comment]
FTR:

```
# curl -fsSL https://github.com/actions/docker/raw/master/login/Dockerfile | \
sed 's/COPY.*//g' |  \
docker build -t actions/docker -

# docker run --rm -e DOCKER_USERNAME="****" -e DOCKER_PASSWORD="****" actions/docker
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

**Comment by 1138-4EB** [comment]
Ref #Azure/container-actions#3
Ref #actions/starter-workflows#96

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
