### ISSUE TITLE
Usability of docker build

### ISSUE THREAD

**Issue by mikeparker** [actions/docker#24]
## Docker build is confusing to set up
I guess this is a very common use case, but I don't see any docs about it.

When typing in 'docker' into the actions, they are ordered as
-> docker tag
-> docker registry
-> Github actions for docker

Firstly, surely if we're going to have a separate action for `docker tag`, shouldnt we have one for `docker build`? After all building my application is before any tagging.

Secondly, the boxes are not clear at all. `Runs` has a tooltip of `Overrides ENTRYPOINT`, which means nothing to the average developer. The fact that an action is running inside a docker container should be an implementation detail, and `ENTRYPOINT` does not give me any hints as to what should go in the box. It also is not clear whether I need to use the `docker` prefix. Do I need to type `docker build` or just `build`? The action is 'for docker' so maybe I just specify which docker command to use?

`args` is unclear because the `runs` box is plenty big enough to type a bunch of arguments, so why do we need a separate args box? is it optional? Do I put just `build` in the first box, and then the tag in the 2nd box? Again the tooltip `Overrides CMD` is useless to me.

## Documentation / Lack of examples
The docs in this repo show:

```
action "build" {
  uses = "actions/docker/cli@master"
  args = "build -t user/repo ."
}
```
These boxes don't even match the UI boxes! In the UI i can edit `label`, `runs` and `args`. Only one of these is in the above snippet, which seems to imply I don't put anything in the `runs` box and put everything in the `args` box? Is `action "build"` the same as `label`?

Next, you have a screenshot on the github actions front page of a different set of fields for a docker build:
https://github.com/features/actions
![image](https://user-images.githubusercontent.com/1557887/61293475-a92cdc80-a7cb-11e9-960a-230b259fb5a1.png)
This has nothing in the `args` box at all, so which is it?

Also, the command is not valid `docker build -t octoverse` is missing the dockerfile location so running this on the command line doesn't even work. Is the dockerfile location somehow inferred from github actions, or is this just a mistake in the image?

## Comparison to Docker Hub Autobuild
To compare this to autobuilds from Docker Hub, for example, all I need to do is type in which branch I want to build from and the location of my dockerfile.

![image](https://user-images.githubusercontent.com/1557887/61293850-86e78e80-a7cc-11e9-9799-6b469e87eeea.png)

This even has the ability to easily tag images from a git tag. The key here is that they provide examples. I think a few examples in the readme here would go a long way.

## Final thoughts
I guess maybe the reason why this is unusable is that its a generic catch all action for all possible docker actions, and that there was an assumption that someone would publish a more specific `docker build` action template? Please let me know if thats the case as maybe I can just make one.

**Comment by jdickey** [comment]
More than nine days later, no follow-up or response at all. I’m a _lot_ less excited about GitHub Actions than I was 24 hours ago, and this is a big part of why.

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
