### ISSUE TITLE
Github environment variables conflicting documentation

### ISSUE THREAD

**Issue by elgohr** [actions/docker#26]
Sticking to the old documentation (https://help.github.com/en/articles/virtual-environments-for-github-actions#default-environment-variables) `GITHUB_SHA` would be a valid environment variable.
With the new workflow enabled, `github.sha` (https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions#contexts) is correct.
This is not really clearly documented.

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
