### ISSUE TITLE
Docker Image Tagging Forbidden

### ISSUE THREAD

**Issue by thomasbarton** [actions/docker#3]
Docker cant find image to run `tag` command on.  I have setup a few other github workflow and have had no issues.  The one difference with this workflow is that the Dockerfile im building is not located in the root of the project.  It is located `unifi_controller/Dockerfile`.

The build step succeeds and ends with success
```
Successfully built 9166e7796c52
Successfully tagged unifi-controller:latest
```

I dont know how github actions is handling securing the docker daemon but my guess is it is based off the location of the Dockerfile and since im executing the docker build command in a subdirectory of my project I cant see the resulting image when executing a docker tag command in the root directory of my project.

This is my worflow
```
workflow "Build and Deploy" {
  on = "push"
  resolves = ["Push image to GCR"]
}

# Build

action "Build Docker image" {
  uses = "actions/docker/cli@master"
  args = ["build", "-t", "unifi-controller", "unifi_controller/."]
}

# Deploy Filter
action "Deploy branch filter" {
  needs = ["Set Credential Helper for Docker"]
  uses = "actions/bin/filter@master"
  args = "branch master"
}

# GKE

action "Setup Google Cloud" {
  uses = "actions/gcloud/auth@master"
  secrets = ["GCLOUD_AUTH"]
}

action "Tag image for GCR" {
  needs = ["Setup Google Cloud", "Build Docker image"]
  uses = "actions/docker/tag@master"
  env = {
    PROJECT_ID = "<removed>"
    APPLICATION_NAME = "unifi-controller"
  }
  args = ["unifi-controller", "gcr.io/$PROJECT_ID/$APPLICATION_NAME", "--no-latest"]
}

action "Set Credential Helper for Docker" {
  needs = ["Setup Google Cloud", "Tag image for GCR"]
  uses = "actions/gcloud/cli@master"
  args = ["auth", "configure-docker", "--quiet"]
}

action "Push image to GCR" {
  needs = ["Setup Google Cloud", "Deploy branch filter"]
  uses = "actions/gcloud/cli@master"
  runs = "sh -c"
  env = {
    PROJECT_ID = "<removed>"
    APPLICATION_NAME = "unifi-controller"
  }
  args = ["docker push gcr.io/$PROJECT_ID/$APPLICATION_NAME"]
}
```

**Comment by thepwagner** [comment]
Thanks for the excellent bug report!

This was an issue affecting all Docker operations performed by Actions (i.e. it could be reproduced with `docker://docker:18.09`, not just `actions/docker/tag@master`).

This was resolved yesterday - `docker tag` is allowed.

**Comment by thomasbarton** [comment]
no problem @thepwagner 
I will test this later this week and then close the issue once confirming :)

**Comment by vovimayhem** [comment]
It's still not working for me...

**Comment by vovimayhem** [comment]
I found out that image names with slashes have something to do with it:

```
workflow "Build and Deploy" {
  on = "push"
  resolves = ["Push image to ECR"]
}

# Build

action "Build Docker image" {
  uses = "actions/docker/cli@master"
  env = {
    IMAGE_NAME = "namespace/aws-example"
  }
  args = ["build", "-t", "$IMAGE_NAME", "artanis"]
}

# AWS

action "Login to ECR" {
  uses = "actions/aws/cli@master"
  secrets = ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"]
  env = {
    AWS_DEFAULT_REGION = "us-west-2"
  }
  args = "ecr get-login --no-include-email --region $AWS_DEFAULT_REGION | sh"
}

action "Tag image for ECR" {
  needs = ["Build Docker image"]
  uses = "actions/docker/tag@master"
  env = {
    CONTAINER_REGISTRY_PATH = "SOMEAWSID.dkr.ecr.us-west-2.amazonaws.com"
    IMAGE_NAME = "namespace/aws-example"
  }
  args = ["$IMAGE_NAME", "$CONTAINER_REGISTRY_PATH/$IMAGE_NAME"]
}

action "Push image to ECR" {
  needs = ["Login to ECR", "Tag image for ECR"]
  uses = "actions/docker/cli@master"
  env = {
    CONTAINER_REGISTRY_PATH = "SOMEAWSID.dkr.ecr.us-west-2.amazonaws.com"
    IMAGE_NAME = "namespace/aws-example"
  }
  args = ["push", "$CONTAINER_REGISTRY_PATH/$IMAGE_NAME"]
}
```

This one fails. After replacing `namespace/aws-example` with `aws-example`, everything works.

**Comment by thomasbarton** [comment]
@ScottBrenner the first `Forbidden` happens to me too.  I believe it happens because there is a docker inspect command that the general public cant run
-> https://github.com/actions/docker/blob/master/tag/tag.rb#L32

I think this error is safe to ignore.  I believe that if you see the log `tagging X as Y` the tag was correctly applied.

Have you tried consuming the tag?

**Comment by thomasbarton** [comment]
@thepwagner This issue has been resolved for me and i can tag images where the Dockerfile is not located in the root.

@vovimayhem You might want to open up a new issue.  Not sure if it is the same issue.

**Comment by thepwagner** [comment]
@vovimayhem the issue with tags containing slashes should now be resolved.

**Comment by thomasbarton** [comment]
closing this issue as it seems to be solved for everyone
