### ISSUE TITLE
Unable to pass array of strings to cli-multi actions

### ISSUE THREAD

**Issue by abeltanjq** [actions/docker#33]
I tried passing an array of strings as arg but could not as mention here:
https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepswithargs
And so I tried the method below since it is a valid yml syntax but could not work too.
Eg.
- name: My step
  uses: actions/docker/cli@master
  with:
        args:
          - 'arg 1'
          - 'arg 2`

May I know how to use this action correctly?

**Comment by starcraft66** [comment]
Experiencing the same issue here... I get "A sequence was not expected".

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
