### ISSUE TITLE
tag calls `docker inspect`

### ISSUE THREAD

**Issue by thepwagner** [actions/docker#6]
As an Actions user,
I want `uses = actions/docker/*` actions to use only whitelisted Docker operations,
So that I'm not wasting Action execution time making dead requests,
So that I don't have confusing error messages in my output.

Extracted from https://github.com/actions/docker/issues/3#issuecomment-443922269 / https://github.com/actions/docker/blob/master/tag/tag.rb#L32

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
