### ISSUE TITLE
Mount image, Operation is forbidden by GitHub Actions - Build Android Application

### ISSUE THREAD

**Issue by chpetersen** [actions/docker#7]
Hello, so I have really been looking forward to these github actions, but I can't figure out how to use it for my needs.

I have this docker image, which contains the Java and Android SDK.
I wan't to pull this image into GitHubActions (Which is working fine), mount it and build my android app from within the image.

But when I try to run this command:  
```
action "build app" {
  uses = "actions/docker/cli@04185cf"
  needs = ["Download android image"]
  args = "run --rm  \\-v $(pwd):/workspace \\-w /workspace android:27.0.3 ./gradlew assembleDevDebug"
}
```

I get the following error:

`docker: Error response from daemon: This Docker operation is forbidden by GitHub Actions, you can find documentation at https://developer.github.com/actions/.`

Is there any way I can achieve this via GitHubActions?

**Comment by nickvanw** [comment]
Hey @chpetersen!

I believe what you would want to do is run that container directly without using the `docker` container and `docker run` as an intermediary. 

You should be able to do this by passing the path to your Dockerfile (not including the `Dockerfile` itself) in your `uses` block. If this `Dockerfile` is in the root of your repo, I believe it would just be doing `uses = ./.`. 

Give that a try and let me know how it goes!

**Comment by webknjaz** [comment]
And yet, can we spawn containers from within Actions?

**Comment by DannyBen** [comment]
Same as @webknjaz , I am also curious. I am trying to understand if it is possible to have an action run a `docker-compose` command with the context of the git repo, so that I can do `docker-compose run tests` and have a complete 3rd-party-less CI/CD solution right here and now.

**Comment by thepwagner** [comment]
@DannyBen  `docker-compose` is not supported at this time, we understand this need but don't have a timeline for releasing the feature yet.
I want this too - docker-compose to run tests with a throwaway database etc is a great pattern!

Spawning containers is allowed, but several functions (e.g. `-v` volume mounting used in the OP) are disabled to prevent a potentially malicious action from accessing other running actions.

**Comment by mharris717** [comment]
@nickvanw are there docs that just list and describe the functionality available, in more of an API docs format? I feel there's a ton of great functionality here, but all the docs are more tutorial or use case focused, and I've been finding it very difficult to just find out what I can do.

**Comment by webknjaz** [comment]
Interestingly, I also face this problem when using docker python package which doesn't do volume mounting

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
